controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    robot_1_diff_cont:
      type: diff_drive_controller/DiffDriveController

    robot_1_joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot_1_piston_cont:
      type: forward_command_controller/ForwardCommandController

    robot_2_diff_cont:
      type: diff_drive_controller/DiffDriveController

    robot_2_joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot_2_piston_cont:
      type: forward_command_controller/ForwardCommandController

    robot_3_diff_cont:
      type: diff_drive_controller/DiffDriveController

    robot_3_joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot_3_piston_cont:
      type: forward_command_controller/ForwardCommandController

    robot_4_diff_cont:
      type: diff_drive_controller/DiffDriveController

    robot_4_joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot_4_piston_cont:
      type: forward_command_controller/ForwardCommandController

    robot_5_diff_cont:
      type: diff_drive_controller/DiffDriveController

    robot_5_joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    robot_5_piston_cont:
      type: forward_command_controller/ForwardCommandController

robot_1_diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.407
    wheel_radius: 0.05

    use_stamped_vel: false

    # open_loop: false

    # wheels_per_side: x
    # wheel_separation_multiplier: x
    # left_wheel_radius_multiplier: x
    # right_wheel_radius_multiplier: x

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    # cmd_vel_timeout: x
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x


    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN




# joint_broad:
#   ros__parameters:

robot_1_piston_cont:
  ros__parameters:

    joints:
      - joint_piston
    interface_name: position
    # pid: {p: 1000, i: 0, d: 0}
    # constraints:
    #   stopped_velocity_tolerance: 0.01 # Defaults to 0.01
    #   goal_time: 0.0 # Defaults to 0.0 (start immediately)

robot_2_diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.407
    wheel_radius: 0.05

    use_stamped_vel: false

robot_2_piston_cont:
  ros__parameters:

    joints:
      - joint_piston
    interface_name: position
    # pid: {p: 1000, i: 0, d: 0}
    # constraints:
    #   stopped_velocity_tolerance: 0.01 # Defaults to 0.01
    #   goal_time: 0.0 # Defaults to 0.0 (start immediately)

robot_2_diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.407
    wheel_radius: 0.05

    use_stamped_vel: false

robot_2_piston_cont:
  ros__parameters:

    joints:
      - joint_piston
    interface_name: position
    # pid: {p: 1000, i: 0, d: 0}
    # constraints:
    #   stopped_velocity_tolerance: 0.01 # Defaults to 0.01
    #   goal_time: 0.0 # Defaults to 0.0 (start immediately)

robot_3_diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.407
    wheel_radius: 0.05

    use_stamped_vel: false

robot_3_piston_cont:
  ros__parameters:

    joints:
      - joint_piston
    interface_name: position
    # pid: {p: 1000, i: 0, d: 0}
    # constraints:
    #   stopped_velocity_tolerance: 0.01 # Defaults to 0.01
    #   goal_time: 0.0 # Defaults to 0.0 (start immediately)


robot_3_diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.407
    wheel_radius: 0.05

    use_stamped_vel: false

robot_3_piston_cont:
  ros__parameters:

    joints:
      - joint_piston
    interface_name: position
    # pid: {p: 1000, i: 0, d: 0}
    # constraints:
    #   stopped_velocity_tolerance: 0.01 # Defaults to 0.01
    #   goal_time: 0.0 # Defaults to 0.0 (start immediately)

robot_4_diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.407
    wheel_radius: 0.05

    use_stamped_vel: false

robot_4_piston_cont:
  ros__parameters:

    joints:
      - joint_piston
    interface_name: position
    # pid: {p: 1000, i: 0, d: 0}
    # constraints:
    #   stopped_velocity_tolerance: 0.01 # Defaults to 0.01
    #   goal_time: 0.0 # Defaults to 0.0 (start immediately)

robot_5_diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.407
    wheel_radius: 0.05

    use_stamped_vel: false

robot_5_piston_cont:
  ros__parameters:

    joints:
      - joint_piston
    interface_name: position
    # pid: {p: 1000, i: 0, d: 0}
    # constraints:
    #   stopped_velocity_tolerance: 0.01 # Defaults to 0.01
    #   goal_time: 0.0 # Defaults to 0.0 (start immediately)

