controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    piston_cont:
      type: forward_command_controller/ForwardCommandController




# joint_broad:
#   ros__parameters:



piston_cont:
  ros__parameters:

    joints: ['joint_piston']
    interface_name: position
    pid: {p: 5000, i: 0, d: 0}
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)