controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Position controller for piston
    # piston_cont:
      # type: forward_command_controller/ForwardCommandController

    piston_vel_cont:
      type: velocity_controllers/JointGroupVelocityController



# joint_broad:
#   ros__parameters:


# Position controller for piston
# piston_cont:
#   ros__parameters:

#     joints: ['joint_piston']
#     interface_name: position
#     pid:
#       p: .1
#       i: .1
#       d: 0
#     constraints:
#       stopped_velocity_tolerance: 0.01 # Defaults to 0.01
#       goal_time: 0.0 # Defaults to 0.0 (start immediately)

piston_vel_cont:
  ros__parameters:
    joints: ['joint_piston']
